# Generated by Django 3.2.16 on 2023-05-04 11:56
import logging

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_fhir_r4", "0005_auto_20221012_0818"),
        ("core", "0015_missing_roles"),
    ]

    operations = [
    ]
